import React, { Component } from 'react'

export default class About extends Component {
    render() {
        return (
            <div>
            <h1>
                About
            </h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus eligendi earum laudantium dolorem praesentium a incidunt tempore, numquam obcaecati quia illum nesciunt molestias, eius excepturi dolor sit voluptatibus minus maiores possimus libero consequuntur laborum! At adipisci eveniet laborum, sed voluptas laboriosam sint saepe hic minus voluptatibus optio esse culpa atque magnam cum! Saepe labore natus a unde error atque earum nisi itaque, odio delectus repudiandae fuga debitis, eveniet porro iusto ex magni molestiae pariatur asperiores doloremque! Quisquam suscipit, officiis assumenda commodi, itaque expedita animi provident ut iusto rem dolores non at asperiores architecto adipisci! Culpa quos totam ut. Amet fugiat cumque nemo maxime, quo veniam quae, voluptas quia autem a voluptatum. Reprehenderit ipsum, error rem impedit ipsa possimus ex sed repudiandae architecto velit autem facilis facere voluptates corrupti eveniet nostrum. Aperiam maxime inventore, ex voluptatem quas cumque pariatur excepturi porro, corrupti suscipit dolore repellat temporibus! Labore deserunt beatae voluptas repellendus, corporis laborum voluptates eius fuga dolore vero saepe nisi culpa ad id cum exercitationem molestiae sequi, aliquam adipisci inventore enim? Minus eveniet ut corporis nisi inventore iusto? Facere sunt eum magnam impedit eius, asperiores, explicabo nihil amet nisi, inventore corrupti sequi quos deleniti fuga. Laboriosam explicabo eligendi deleniti quibusdam harum tempora dolores repellat, laborum nihil eius, labore tempore consequatur veniam similique dicta vitae porro. Consequatur rem saepe veniam corporis cupiditate, tempora aspernatur libero sequi quo distinctio asperiores quibusdam itaque sit repellat nemo magni consequuntur deserunt totam. Maxime architecto quis perferendis, ea aperiam libero voluptas labore ipsum et quae molestias eos deserunt mollitia quasi consequuntur voluptatum temporibus quia, dicta veniam saepe. Dignissimos distinctio molestias molestiae, voluptatum iusto ea nesciunt esse cum qui excepturi iste ab quaerat ad nihil tenetur nulla quos. Voluptatem ex dicta quod id pariatur autem perferendis debitis rerum earum recusandae vitae sunt, optio officiis ut, nihil repellat qui?</p>
            <br />
            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Asperiores eveniet illo libero sed sequi enim iste pariatur numquam quas similique! Cupiditate aperiam dolore natus. Dicta magni reiciendis placeat! Eveniet impedit id iste quibusdam at voluptas eos enim qui aspernatur adipisci. Fugit, quidem fugiat? Repudiandae ipsum amet molestias iusto quaerat veniam aliquid delectus nostrum repellat, a necessitatibus odio aperiam dolorum ut maxime asperiores explicabo suscipit fugiat illum voluptatum culpa quidem numquam at debitis? Exercitationem ipsum nulla perferendis dignissimos quidem sequi, veritatis dicta veniam excepturi ullam iste est, totam porro alias possimus. Laboriosam totam ipsam saepe, officiis sit minima enim? Facilis, enim.</p>
            </div>
        )
    }
}
